name: 东东工厂

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_jdfactory

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【东东工厂】"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  JD_USER_AGENT: ${{ github.event.client_payload.JD_USER_AGENT || secrets.JD_USER_AGENT }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  FACTORAY_WANTPRODUCT_NAME: ${{ github.event.client_payload.FACTORAY_WANTPRODUCT_NAME || secrets.FACTORAY_WANTPRODUCT_NAME }}
                  DDFACTORY_SHARECODES: ${{ github.event.client_payload.DDFACTORY_SHARECODES || secrets.DDFACTORY_SHARECODES }}
                  GITHUB: ${{ github.event.client_payload.GITHUB || secrets.GITHUB }}
                  SYNCURL: https://github.com/an0na/jd_scripts/raw/master/jd_jdfactory.js
                  IGNORE_COOKIE_JDGC: ${{ github.event.client_payload.IGNORE_COOKIE_JDGC || secrets.IGNORE_COOKIE_JDGC }} #京东工厂禁用某些cookie的执行,因为通知太烦了呀,比如要禁用第2和第四个的执行,则填入[2,4]即可,包含中括号哦
