# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 口袋书店

on:
    workflow_dispatch:
    schedule:
        - cron: "1 8,12,18 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_bookshop

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【口袋书店】"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  BOOKSHOP_SHARECODES: ${{ github.event.client_payload.BOOKSHOP_SHARECODES || secrets.BOOKSHOP_SHARECODES }}
                  GITHUB: ${{ github.event.client_payload.GITHUB || secrets.GITHUB }}
                  SYNCURL: https://github.com/an0na/jd_scripts/raw/master/jd_bookshop.js
                  IGNORE_COOKIE_BOOKSHOP: ${{ github.event.client_payload.IGNORE_COOKIE_BOOKSHOP || secrets.IGNORE_COOKIE_BOOKSHOP }} #口袋书店禁用某些cookie的执行,因为通知太烦了呀,比如要禁用第2和第四个的执行,则填入[2,4]即可,包含中括号哦
