name: 京喜农场

on:
    workflow_dispatch:
    schedule:
        - cron: "0 1,10 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_jxnc

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【京喜农场】"
              run: |
                  node onlyOneExecute.js
              env:
                  JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }}
                  JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }}
                  TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }}
                  GITHUB: ${{ github.event.client_payload.GITHUB || secrets.GITHUB }}
                  SYNCURL: https://github.com/an0na/jd_scripts/raw/master/jd_jxnc.js
                  #专属配置
                  JXNC_SHARECODES: ${{ github.event.client_payload.JXNC_SHARECODES || secrets.JXNC_SHARECODES }}
                  JXNCTOKENS: ${{ github.event.client_payload.JXNCTOKENS || secrets.JXNCTOKENS }}
                  IGNORE_COOKIE_JXNC: ${{ github.event.client_payload.IGNORE_COOKIE_JXNC || secrets.IGNORE_COOKIE_JXNC }} #京喜农场禁用某些cookie的执行,因为通知太烦了呀,比如要禁用第2和第4个的执行,则填入[2,4]即可,包含中括号哦
